import type { Metadata } from "next";
// ❌ 删除：import localFont from "next/font/local"; (导致报错的元凶)
import "./globals.css";
import Navbar from "./components/Navbar"; 
import Footer from "./components/Footer";
import { ClerkProvider } from '@clerk/nextjs'

// ❌ 删除：const geistSans = ...
// ❌ 删除：const geistMono = ...

export const metadata: Metadata = {
  title: "ArTD Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* ❌ 删除：className 中的 geist 变量 */}
        <body className="antialiased">
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}